function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "AZSpawn", file = "media/maps/AZSpawn/spawnpoints.lua" },
		{ name = "Many Spawns Louisville", file = "media/maps/Many Spawns Louisville/spawnpoints.lua" },
		{ name = "Audubon", file = "media/maps/Audubon/spawnpoints.lua" },
		{ name = "Central Louisville", file = "media/maps/Central Louisville/spawnpoints.lua" },
		{ name = "Evergreen Hill", file = "media/maps/Evergreen Hill/spawnpoints.lua" },
		{ name = "Old Louisville", file = "media/maps/Old Louisville/spawnpoints.lua" },
		{ name = "Phoenix Hill", file = "media/maps/Phoenix Hill/spawnpoints.lua" },
		{ name = "Many Spawns Casual", file = "media/maps/Many Spawns Casual/spawnpoints.lua" },
		{ name = "Many Spawns root", file = "media/maps/Many Spawns root/spawnpoints.lua" },
		{ name = "Many Spawns All", file = "media/maps/Many Spawns All/spawnpoints.lua" },
		{ name = "Rosewood", file = "media/maps/Rosewood/spawnpoints.lua" },
		{ name = "Valley Station", file = "media/maps/Valley Station/spawnpoints.lua" },
		{ name = "Dixie", file = "media/maps/Dixie/spawnpoints.lua" },
		{ name = "Ekron", file = "media/maps/Ekron/spawnpoints.lua" },
		{ name = "Industrial Zone", file = "media/maps/Industrial Zone/spawnpoints.lua" },
		{ name = "March Ridge", file = "media/maps/March Ridge/spawnpoints.lua" },
		{ name = "McCoy Logging", file = "media/maps/McCoy Logging/spawnpoints.lua" },
		{ name = "Muldraugh", file = "media/maps/Muldraugh/spawnpoints.lua" },
		{ name = "Riveside", file = "media/maps/Riveside/spawnpoints.lua" },
		{ name = "West Point", file = "media/maps/West Point/spawnpoints.lua" },
		{ name = "By Profession", file = "media/maps/By Profession/spawnpoints.lua" },
		{ name = "Many Spawns All Reduced", file = "media/maps/Many Spawns All Reduced/spawnpoints.lua" },
		{ name = "Many Spawns Knox Reduced", file = "media/maps/Many Spawns Knox Reduced/spawnpoints.lua" },
		{ name = "Knox County Building Inspector", file = "media/maps/Knox County Building Inspector/spawnpoints.lua" },
		{ name = "Knox County Car Wrecks", file = "media/maps/Knox County Car Wrecks/spawnpoints.lua" },
		{ name = "Knox County Hitchhikers", file = "media/maps/Knox County Hitchhikers/spawnpoints.lua" },
		{ name = "Knox County Patients", file = "media/maps/Knox County Patients/spawnpoints.lua" },
		{ name = "Knox County Prisoners", file = "media/maps/Knox County Prisoners/spawnpoints.lua" },
		{ name = "Knox County Schools", file = "media/maps/Knox County Schools/spawnpoints.lua" },
		{ name = "Knox County Visitors", file = "media/maps/Knox County Visitors/spawnpoints.lua" },
	}
end
